-- Mail Ninja database seed
-- Generated by scripts/build-database-seed.ts.
--
-- Regenerate with: npm run db:seed-sql
-- Verify freshness with: npm run db:seed-sql:check
--
-- This seed creates a neutral default workspace, sender settings, and one
-- default administrator for a fresh installation.
--
-- Default admin:
--   Email: admin@example.com
--   Password: adminadminadmin
--
-- Change this password immediately after first login.

with default_workspace as (
  insert into workspaces (
    name,
    slug,
    default_locale,
    timezone
  )
  values (
    'Example Company',
    'default',
    'en',
    'UTC'
  )
  on conflict (slug) do update
    set
      name = excluded.name,
      default_locale = excluded.default_locale,
      timezone = excluded.timezone,
      updated_at = now()
  returning id
),
selected_workspace as (
  select id from default_workspace
  union all
  select id from workspaces where slug = 'default'
  limit 1
)
insert into workspace_settings (
  workspace_id,
  product_name,
  public_base_url,
  default_from_name,
  default_from_email,
  default_reply_to,
  default_locale,
  timezone,
  provider
)
select
  id,
  'Mail Ninja',
  'http://localhost:3000',
  'Mail Ninja',
  'noreply@example.com',
  'support@example.com',
  'en',
  'UTC',
  'resend'
from selected_workspace
on conflict (workspace_id) do update
  set
    product_name = excluded.product_name,
    public_base_url = excluded.public_base_url,
    default_from_name = excluded.default_from_name,
    default_from_email = excluded.default_from_email,
    default_reply_to = excluded.default_reply_to,
    default_locale = excluded.default_locale,
    timezone = excluded.timezone,
    provider = excluded.provider,
    updated_at = now();

with selected_workspace as (
  select id from workspaces where slug = 'default' limit 1
)
insert into admin_users (
  workspace_id,
  email,
  normalized_email,
  password_hash,
  display_name,
  is_active
)
select
  id,
  'admin@example.com',
  'admin@example.com',
  '$argon2id$v=19$m=19456,t=2,p=1$hV9kibodAk0CpNHEK18KPw$tpbord7T/q0hCs9mjb9d340dskeB9EQvTkPAlUUUqsk',
  'Admin',
  true
from selected_workspace
on conflict (workspace_id, normalized_email) do nothing;
